const RESET_RESERVATIONS = 'RESET_RESERVATIONS';
const ADD_RESERVATION = 'ADD_RESERVATIONS';
const REMOVE_RESERVATION = 'REMOVE_RESERVATION'

const reservationTypes = {
    RESET_RESERVATIONS,
    ADD_RESERVATION,
    REMOVE_RESERVATION
};

export default reservationTypes;